/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
  // RCC base address (from the memory map chapter). Note: end all hex address defines with UL (unsigned long)
  #define RCC_BASE  0x40023800UL

  // AHB1ENR is at offset 0x30
  #define RCC_AHB1ENR  (*(volatile unsigned int *)(RCC_BASE + 0x30))

  // Set bit 3 to enable GPIOD clock. Note: this enables clock for PD0 - PD15
  RCC_AHB1ENR |= (1 << 3);

  // GPIOD base address (from memory map). Note: unsigned long tells compiler to treat it as 32-bit value rather than signed integer
  #define GPIOD_BASE  0x40020C00UL

  // GPIOD_MODER is the first register in GPIOD
  #define GPIOD_MODER (*(volatile unsigned int *)(GPIOD_BASE + 0x00))

  // set bit 24 to configure pin 12 (green LED) of GPIOD to "general purpose output mode"
  GPIOD_MODER |= (1 << 24);
  // also set bit 30 to configure pin 15 (blue LED) of GPIOD to "g/p output mode"
  GPIOD_MODER |= (1 << 30);

  // GPIOD_BSRR (bit set/reset register) is at offset 0x18
  #define GPIOD_BSRR (*(volatile unsigned int *)(GPIOD_BASE + 0x18))

  // set BS12 to 'high' i.e. turn on green LED
  // note: no need for |= here, BSRR is write only
  GPIOD_BSRR = (1 << 12);
  // also set BS15 to 'high' i.e. turn on blue LED
  //GPIOD_BSRR = (1 << 15); --> leave this one off initially for staggered effect

  #define GPIOD_ODR (*(volatile unsigned int *)(GPIOD_BASE + 0x14))

  /* Loop forever */
	while(1) {
    for (volatile int i=1; i<=600000; i++){} // crude delay (no clock initialization currently)
    GPIOD_ODR ^= (1 << 12); // flip ODR12 (pin 12, green LED) every ~0.4s
    GPIOD_ODR ^= (1 << 15); // also flip ODR15 (pin 15, blue LED)
  }
}
